<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'guest' => 'Гость',
    'Access management' => 'Управление доступами',
    'Accesses management' => 'Управление доступами',
    'Project management' => 'Управление проектами',
    'User management' => 'Управление пользователями',
    'can change setting' => 'может настраивать проект',
    'can change task stage' => 'может менять этап задачи',
    'can close task' => 'может закрывать задачи',
    'can create comment' => 'может создавать комментарии',
    'can edit task' => 'может редактировать задачи',
    'can manage (edit/delete) comment' => 'может управлять комментариями',
    'can open task' => 'может открывать задачи',
    'can see project' => 'Может просматривать проект',
    'root' => 'Суперадмин (root)',
    'user' => 'Пользователь',
];
