<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cannot delete this dict item' => 'Невозможно удалить этот элемент справочника',
    'Cannot reposition this dict item' => 'Невозможно поменять позицию этого элемента справочника',
    'Delete dict item' => 'Удалить элемент справочника',
    'Dict item associated to entities' => 'Некоторые объекты используют этот справочник',
    'Drag and drop to new position' => 'Схватите и передвиньте элемент справочника для смены его позиции в справочнике',
    '#' => '#',
    'Actions' => 'Действия',
    'Assigned entities' => 'Ассоциированные объекты',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Check version as Past' => 'Отметить версию как прошлую',
    'Close' => 'Закрыта',
    'Close task' => 'Работа над задачей завершена',
    'Current' => 'Текущая',
    'Description' => 'Описание',
    'Difficulty' => 'Трудоемкость',
    'Difficulty levels' => 'Уровни сложности',
    'Future' => 'Будущая',
    'ID' => 'ID',
    'Name' => 'Имя',
    'Not closed tasks' => 'Не закрытые задачи',
    'Open' => 'Открыта',
    'Open in version' => 'Обнаружен в версии',
    'Open task' => 'Новая задача',
    'Past' => 'Прошедшая',
    'Position' => 'Позиция',
    'Project ID' => 'ID',
    'Ratio' => 'Коэф. сложности',
    'Stage' => 'Этап',
    'Tasks stages' => 'Этапы выполнения задачи',
    'Tasks types' => 'Типы задач',
    'Tasks versions' => 'Версии проекта',
    'Type' => 'Тип',
    'Сoming in version' => 'Ожидается в версии',
];
