<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Enable comment project' => 'Разрешить комментирование проекта',
    'All' => 'Все',
    'Configuration' => 'Конфигурация',
    'Create Project' => 'Новый проект',
    'Created' => 'Создан',
    'Description' => 'Описание',
    'Empowered' => 'Уполномоченные',
    'Name' => 'Имя',
    'Overview' => 'Обзор',
    'Project Manager' => 'Управление проектами',
    'Project admin' => 'Администратор',
    'Project not found' => 'Проект не найден',
    'Project settings' => 'Настройки проекта',
    'Projects' => 'Проекты',
    'Public' => 'Виден для',
    'Registered' => 'Зарегистрированные',
    'Settings' => 'Настройки',
    'Statistics' => 'Статистика',
    'Suffix' => 'Суффикс',
    'Update {modelClass}: ' => 'Изменить {modelClass}: ',
    'Updated' => 'Обновлен',
    'suffix must be unique' => 'суффикс уже используется',
    'suffix must contain only A-Z or 0-9 chars' => 'суфикс может содержать только символы A-Z и цифры 0-9',
];
