<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Project managers' => 'Управляющие проектом',
    'Are you sure you want to active this project?' => 'Сделать проект вновь активным?',
    'Are you sure you want to archive this project?' => 'Перенести этот проект в архив?',
    'Cannot be edit' => 'Не может быть отредактированно',
    'Cannot change project archive status' => 'Ошибка при смене статуса архивности проекта',
    'Cannot delete project with tasks' => 'Невозможно удаить проект имеющий задачи',
    'Configuration' => 'Конфигурация',
    'Create Project' => 'Новый проект',
    'Created' => 'Создан',
    'Delete project' => 'Удалить проект',
    'Description' => 'Описание',
    'Enable comment to closed tasks' => 'Разрешить комментирование закрытых задач',
    'Enable comment to project' => 'Разрешить комментирование проекта',
    'From archive' => 'Из архива',
    'Name' => 'Имя',
    'Overview' => 'Обзор',
    'Project Manager' => 'Управление проектами',
    'Project activate' => 'Проект активирован',
    'Project admin' => 'Администратор',
    'Project archived' => 'Проект архивирован',
    'Project not found' => 'Проект не найден',
    'Project settings' => 'Настройки проекта',
    'Projects' => 'Проекты',
    'Public' => 'Виден для',
    'Roles and permissions template' => 'Шаблон набора ролей и полномочий',
    'Settings' => 'Настройки',
    'Statistics' => 'Статистика',
    'Suffix' => 'Суффикс',
    'Text editor type' => 'Редактор текста',
    'To archive' => 'В архив',
    'Update Project' => 'Редактировать проект',
    'Updated' => 'Обновлен',
    'suffix must be unique' => 'суффикс уже используется',
    'suffix must contain only A-Z or 0-9 chars' => 'суфикс может содержать только символы A-Z и цифры 0-9',
];
