<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Open task' => 'Открыть задачу',
    'Assigned' => 'Назначена',
    'Cancel' => 'Отменена',
    'Caption' => 'Заголовок',
    'Close reason' => 'Причина закрытия',
    'Close task' => 'Закрыть задачу',
    'Create task' => 'Новая',
    'Created' => 'Создана',
    'Critical' => 'Критический',
    'Description' => 'Описание',
    'Done' => 'Готова',
    'Edit task' => 'Редактировать задачу',
    'Error in create new task' => 'Ошибка при созданиии задачи',
    'High' => 'Высокий',
    'ID' => 'ID',
    'Impossible' => 'Невозможно',
    'Index' => '№ задачи',
    'Low' => 'Низкий',
    'Medium' => 'Обычный',
    'No error' => 'Не ошибка',
    'Priority' => 'Приоритет',
    'Progress' => 'Прогресс',
    'Retry' => 'Повтор',
    'Suffix' => 'суффикс проекта',
    'Task list' => 'Список задач',
    'Task: ' => 'Задача:',
    'Tasks' => 'Задачи',
    'Updated' => 'Обновлена',
    'Very Low' => 'Очень низкий',
    'Very high' => 'Очень высокий',
];
