<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email already exist' => 'Данный email уже используется',
    'Active' => 'Активен',
    'Admin in projects' => 'Админ в проектах',
    'Auth key' => 'Auth key',
    'Blocked' => 'Заблокирован',
    'Change password:' => 'Изменить пароль:',
    'Change username or email:' => 'Изменить имя или email',
    'Confirmation wait' => 'Ожидает подтверждения',
    'Create User' => 'Создать пользователя',
    'Created at' => 'Создан',
    'Email' => 'Email',
    'Email Confirmation Token' => 'Токен подтверждения Email',
    'Fill register fields:' => 'Заполните поля для регистрации:',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Password' => 'Пароль',
    'Password hash' => 'Хеш пароля',
    'Profile ({user})' => 'Профиль ({user})',
    'Registration' => 'Регистрация',
    'Status' => 'Статус',
    'The installation creates superadmin user <strong>admin</strong> with password <strong>root</strong>.
It is strongly recommended to change it immediately' => 'При установке создается суперадмин <strong>root</strong> с паролем <strong>root</strong>.
        Настоятельно рекомендуется его сразу изменить',
    'Update User: ' => 'Редактировать пользователя: ',
    'Updated at' => 'Обновлен',
    'User Manager' => 'Управление пользователями',
    'User profile' => 'Профиль пользователя',
    'User roles' => 'Роли пользователя',
    'User token' => 'Токен пользователя',
    'Username' => 'Имя',
    'Username already exist' => 'Имя пользователя уже используется',
    'You will need to confirm over email' => 'Потребуется подтверждение пользователя через email',
    'register' => 'Зарегистрировать',
    '{user} profile' => 'Профиль пользователя {user}',
];
