<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'From archive' => 'Разархивировать',
    'To archive' => 'В архив',
    'Administrate' => 'Администрировать проект',
    'Are you sure you want to active this project?' => 'Сделать проект вновь активным?',
    'Are you sure you want to archive this project?' => 'Перенести этот проект в архив?',
    'Cannot change project archive status' => 'Ошибка при смене статуса архивности проекта',
    'Cannot delete project with tasks' => 'Невозможно удаить проект имеющий задачи',
    'Delete project' => 'Удалить проект',
    'Enable comment to closed tasks' => 'Разрешить комментирование закрытых задач',
    'Enable comment to project' => 'Разрешить комментирование проекта',
    'Project Manager' => 'Управление проектами',
    'Project activate' => 'Проект активирован',
    'Project archived' => 'Проект архивирован',
    'Roles and permissions template' => 'Шаблон набора ролей и полномочий',
    'Text editor type' => 'Редактор текста',
];
