<?php
/**
 * User: demius
 * Date: 20.12.17
 * Time: 23:31
 */

namespace app\components\textEditors;


use yii\widgets\InputWidget;


class MdEditor extends InputWidget implements ITextEditor
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function render($view, $params = [])
    {
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }
}